<?php

namespace app\controllers;

class Lies extends Api
{
    protected function execute(): array
    {
        return [
            [1, 3, 'Do you believe it, -lieve it'],
            [7, 'When I say it\'s you I needed? Oh'],
            [8, 10, 'It\'s like I\'m dreamin\', dreamin\''],
            [11, 15, '\'Cause you helped me stop the bleedin\', yeah'],
            [16, 20, 'Don\'t wanna be alone tonight'],
            [23, 'Don\'t think too much, let\'s turn off the lights'],
            [27, 'Back and forth like all of the time'],
            [31, 'Know it\'s a lot, but just don\'t think twice'],
            [33, 'Where to go?'],
            [35, 'I don\'t even know'],
            [37, 'Only big white lies to get by'],
            [40, '\'Cause I don\'t wanna make you cry'],
            [42, 'Stay here by my side'],
            [45, 'Only big white lies to get by'],
            [47, '\'Cause, don\'t know where to go, oh'],
            [49, 'I don\'t even know, oh'],
            [53, 'I\'ve been tellin\' you white lies, so you would stay'],
            [55, 'I don\'t wanna make you cry'],
            [57, 'Stay here by my side'],
            [0, 'Only big white lies to get by'],
            [2, '\'Cause I just don\'t know where to go'],
            [4, 'I don\'t even know'],
            [7, 'Only big white lies to get by'],
            [10, '\'Cause I don\'t wanna make you cry'],
            [12, 'Stay here by my side'],
            [15, 'Only big white lies to get by'],
            [17, '\'Cause, don\'t know where to go, oh'],
            [19, 'I don\'t even know, oh'],
            [23, 'I\'ve been tellin\' you white lies, so you would stay'],
            [25, 'I don\'t wanna make you cry'],
            [27, 'Stay here by my side'],
            [30, 'Only big white lies to get by'],
            [32, 'So you can feel it, feel it'],
            [34, 37, 'There\'s this crazy thing between us, oh'],
            [38, 40, 'Don\'t need a reason, reason'],
            [41, 45, 'Where you\'re at, I wanna be there, oh'],
            [46, 50, 'Don\'t wanna be alone tonight'],
            [53, 'Don\'t think too much, let\'s turn off the lights'],
            [57, 'Back and forth like all of the time'],
            [1, 'Know it\'s a lot, but just don\'t think twice'],
            [3, 'Where to go?'],
            [5, 'I don\'t even know'],
            [7, 'Only big white lies to get by'],
            [10, '\'Cause I don\'t wanna make you cry'],
            [12, 'Stay here by my side'],
            [15, 'Only big white lies to get by'],
            [17, '\'Cause, don\'t know where to go, oh'],
            [19, 'I don\'t even know, oh'],
            [23, 'I\'ve been tellin\' you white lies, so you would stay'],
            [25, 'I don\'t wanna make you cry'],
            [27, 'Stay here by my side'],
            [30, 'Only big white lies to get by'],
            [33, 'I just don\'t know where to go'],
            [35, 'I don\'t even know'],
            [37, 'Only big white lies to get by'],
            [40, '\'Cause I don\'t wanna make you cry'],
            [42, 'Stay here by my side'],
            [45, 'Only big white lies to get by'],
            [47, '\'Cause, don\'t know where to go, oh'],
            [49, 'I don\'t even know, oh'],
            [53, 'I\'ve been tellin\' you white lies, so you would stay'],
            [55, 'I don\'t wanna make you cry'],
            [57, 'Stay here by my side'],
            [0, 'Only big white lies to get by']
        ];
    }
}
